ALTER TABLE department
    ADD COLUMN IF NOT EXISTS description VARCHAR(500),
    ADD COLUMN IF NOT EXISTS image_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS accent_color VARCHAR(20),
    ADD COLUMN IF NOT EXISTS bg_color VARCHAR(20),
    ADD COLUMN IF NOT EXISTS icon VARCHAR(20);
