package com.hms.entity.type;

public enum NotificationType {
    APPOINTMENT_CREATED,
    APPOINTMENT_STATUS_CHANGED,
    APPOINTMENT_UPDATED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_PENDING,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REFUND,
    APPOINTMENT_RESCHEDULED,
    BRANCH_DOCTOR_ADDED,
    BRANCH_DEPARTMENT_ADDED
}
