# Here we define the OAuth verification details

# spring.security.oauth2.client:
#     registration:
#         google:
#             client-id: sdkjfsdncusn
#             client-secret: sdjniwklvm
#         github:
#             client-id: pwflmcpalksadc
#             client-secret: onnaloenowej

#Email sender 
spring:
    mail:
        host: ${MAIL_HOST:smtp.gmail.com}
        port: ${MAIL_PORT:587}
        username: ${MAIL_USERNAME:}
        password: ${MAIL_PASSWORD:}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
