# Here we define the OAuth verification details

# spring.security.oauth2.client:
#     registration:
#         google:
#             client-id: sdkjfsdncusn
#             client-secret: sdjniwklvm
#         github:
#             client-id: pwflmcpalksadc
#             client-secret: onnaloenowej

#Email sender 
spring:
    data:
        redis:
            url: ${REDIS_URL}
            repositories:
                enabled: false
    mail:
        host: ${MAIL_HOST:smtp.gmail.com}
        port: ${MAIL_PORT:587}
        username: ${MAIL_USERNAME:}
        password: ${MAIL_PASSWORD:}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

# Swagger/OpenAPI Configuration
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        operations-sorter: method
        tags-sorter: alpha
    api-docs:
        path: /v3/api-docs

# Resilience4j Rate Limiter Configuration
resilience4j:
    ratelimiter:
        configs:
            default:
                limitRefreshPeriod: 1m
                limitForPeriod: 10
                timeoutDuration: 1s
        instances:
            globalRateLimiter:
                baseConfig: default
            authRateLimiter:
                limitRefreshPeriod: 1m
                limitForPeriod: 10
                timeoutDuration: 1s
            userRateLimiter:
                limitRefreshPeriod: 1m
                limitForPeriod: 20
                timeoutDuration: 1s
            readOnlyRateLimiter:
                limitRefreshPeriod: 1m
                limitForPeriod: 20
                timeoutDuration: 1s
            adminRateLimiter:
                limitRefreshPeriod: 1m
                limitForPeriod: 30
                timeoutDuration: 1s
